### ISSUE TITLE
Add support for OpenSearch Vector database

### ISSUE THREAD

**Issue by vamshin** [hwchase17/langchain#1054]
OpenSearch supports approximate vector search powered by Lucene engine, nmslib engine, faiss engine and also bruteforce vector search using painless scripting functions.  As OpenSearch is popular search engine, it would be good to have this available as one of the supported vector database

**Comment by naveentatikonda** [comment]
I'm working on this. Thanks!

**Comment by naveentatikonda** [comment]
@ZohaibRamzan I got your problem. You might have used a different name for the knn vector field name instead of the default name `vector_field` when you created the index and ingested the data into it.

So, as you are not specifying the same field name during search, it is taking the default field name `vector_field` and trying to build the query which is causing this error 
```
RequestError: RequestError(400, 'search_phase_execution_exception', "failed to create query: Field 'vector_field' is not knn_vector type.")
```

To fix this send the custom field name that you have used as an argument like shown below:
```
docs = docsearch.similarity_search(query, k=1,search_type = "approximate_search", vector_field="custom_field")
```

Also, one more suggestion, for Approximate Search if you want to use a different `space_type` instead of default value `l2`, we need to specify it while creating the index. So, send it as an argument during ingestion.

**Comment by kiranshivaraju** [comment]
can you show how to add the custom field name while creating the index

**Comment by ggayathri2504** [comment]
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import OpenSearchVectorSearch
from langchain.document_loaders import TextLoader
import os
os.environ['OPENAI_API_KEY'] = "T3BlbkFJLYcualaylRoioixxxxx"
docsearch = OpenSearchVectorSearch(index_name="address_search", embedding_function=embeddings, opensearch_url="aws url")

This is my code, the document is converted into vectors and stored in the elastic search (OpenSearch ) successfully but while querying something using the below code, it returns empty list.

query="Give me the address of id no 13501"
docs = docsearch.similarity_search(query, k=1,search_type = "approximate_search",space_type = "cosinesimil")

**Comment by wcheek** [comment]
For anyone here looking to address the error `'search_phase_execution_exception', "failed to create query: Field 'vector_field' is not knn_vector type."`, you need to add the `vector_field` param as a `**kwarg` in your instantiation of `OpenSearchVectorSearch`

**Comment by Sinan-Karakaya** [comment]
> For anyone here looking to address the error `'search_phase_execution_exception', "failed to create query: Field 'vector_field' is not knn_vector type."`, you need to add the `vector_field` param as a `**kwarg` in your instantiation of `OpenSearchVectorSearch`

@wcheek Could you elaborate please ? I am using the rag-opensearch template with minimal changes, but I still get the same error, with this instantiation:

```python
vector_store = OpenSearchVectorSearch(
    opensearch_url=OPENSEARCH_URL,
    http_auth=(OPENSEARCH_USERNAME, OPENSEARCH_PASSWORD),
    index_name=OPENSEARCH_INDEX_NAME,
    embedding_function=embedding_function,
    verify_certs=False,
    vector_field="my-vector-field-name"
)
```

**Comment by wcheek** [comment]
@Sinan-Karakaya I ended up not using this option in the end so I no longer have an example. Now I just use the default vector field name, "vector_field". I would advise this if you are able to since this is always the expected name when using `langchain`. 

Are you able to check your index mappings in Kibana to verify that your vector field is indeed what you expect it to be? You can check out the [source code](https://github.com/langchain-ai/langchain/blob/2b234a4d96d66af47a8b51284141d74decfc2251/libs/community/langchain_community/vectorstores/opensearch_vector_search.py#L309C15-L309C16) and see that the `**kwarg` is indeed `vector_field` and see how it gets used - maybe there is something missing that is causing your issue.

**Comment by Sinan-Karakaya** [comment]
@wcheek I ended fixing my issue, it actually had to do with how I initialised the client. However I did had to stick to the default `vector_field` name. Thanks !

**Comment by progpyftk** [comment]
Having some trouble as well when using is as a retriever. But when I make the search using the vectorstore obj it works.

# opensearch vectorstore
```
lessons_10000_0_vectorstore = OpenSearchVectorSearch(
        embedding_function = azure_embeddings,
        index_name = "lessons_recursive_10000_0",
        http_auth = ('admin', os.getenv("OPENSEARCH_INITIAL_ADMIN_PASSWORD")),
        use_ssl = True,
        verify_certs = False,
        ssl_assert_hostname = False,
        ssl_show_warn = False,
        opensearch_url="http://localhost:9200",
        text_field="text",
        metadata_field="metadata",
        vector_field="lessons_vector",
        search_type = "approximate_search",
    )
```

```
# creates a retriever
lessons_10000_0_retriever = lessons_10000_0_vectorstore.as_retriever()
```

```
# find the docs
found_docs = await lessons_10000_0_retriever.aget_relevant_documents(query)
```
>>opensearchpy.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', "failed to create query: Field 'vector_field' is not knn_vector type.")

 When I make the search from vectorstore instead of building a retriever it works fine:

```
found_docs = await lessons_10000_0_vectorstore.asimilarity_search(
            query,
            vector_field="lessons_vector",
            text_field="text",
            metadata_field="metadata",
            search_type="approximate_search", 
       ) 
```  

I think the function retriever.aget_relevant_documents is not able to understand the vector_field parameter.

**Comment by progpyftk** [comment]
Update: Everything works fine when I set the field_vector in the properties "properties": and vector_field = "vector_field " when adding the docs:


```
        index_body = {
            'settings': {
                "index.knn": True
            },
            "mappings": {
                "properties": {
                "**lessons_vector**": {
                    "type": "**knn_vector**",
                    "dimension": 1536,
                    ........

 
    
            .....
            self.vectorstore.add_documents(
                documents = batch,
                **vector_field** = "vector_field"
            )
            logger.info(f"Batch {i // self.batch_size} processed successfully.")
           ......
```
