### ISSUE TITLE
Not able to use the chat agent

### ISSUE THREAD

**Issue by asmithar** [hwchase17/langchain#1574]
I get the following error when running the mrkl_chat.ipyb notebook  : https://github.com/hwchase17/langchain/blob/master/docs/modules/agents/implementations/mrkl_chat.ipynb

`Invalid format specifier (type=value_error)`

**Comment by pengqu123** [comment]
Me too.  the error detail is : 
![image](https://user-images.githubusercontent.com/82029664/224234476-2b09d96e-560f-4ca8-afca-9c7ef58de3f2.png)

@hwchase17  the root cause is  after  " Formatter().parse(template)"
we will get an input_variables  '\n  "action"'
here is the frist tuple after  Formatter().parse: 

 ('Answer the following questions as best you can. You have access to the following tools:\n\nSearch: useful for when you need to answer questions about current events. You should ask targeted questions\nCalculator: useful for when you need to answer questions about math\n\nThe way you use the tools is by specifying a json blob.\nSpecifically, this json should have a `action` key (with the name of the tool to use) and a `action_input` key (with the input to the tool going here).\n\nThe $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:\n\n```\n', '\n  "action"', ' "calculator",\n  "action_input": "1 + 2"\n', None)

**Comment by hwchase17** [comment]
sorry about that. put up a pr that should fix

**Comment by asmithar** [comment]
Thank you!
