### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by LeiSanity** [hwchase17/langchain#2074]
from langchain.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(file_path='docs/whats-new-latest.csv', csv_args={
    'fieldnames': ['Line of Business', 
                   'Short Description'
                   ]
})
data = loader.load()
print(data)

/.pyenv/versions/3.9.2/envs/s4-hana-chatbot/lib/python3.9/site-packages/langchain/document_loaders/csv_loader.py", line 53, in <genexpr>
    content = "\n".join(f"{k.strip()}: {v.strip()}" for k, v in row.items())
AttributeError: 'NoneType' object has no attribute 'strip'

Can anyone assist how to solve this?

**Comment by lenaten** [comment]
Same here, did you get it sorted out?

**Comment by Nazacheres** [comment]
Hi, @LeiSanity how did you resolve this?

**Comment by ezzcodeezzlife** [comment]
Hey, same issue

**Comment by MogwaiMomo** [comment]
Also having the same issue

**Comment by othyn** [comment]
Same issue!

**Comment by MogwaiMomo** [comment]
@othyn I don't know if this is an option for you but I just switched over to using the Pandas Dataframe Loader https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/pandas_dataframe.html 

and it works fine :)

**Comment by othyn** [comment]
@MogwaiMomo Thank you!

I was using it as part of privateGPT - so don't really have a choice on libraries unfortunately. Although interestingly it does have pandas support, but thats one for the maintainers.

Although I think the original problem was caused by something in the data formatting of the ingesting CSV.

Instead of debugging the application, I looked to debugging the data instead and that seemed to fix things. Althouh, as I just wiped out all the columns I wasn't using, so I'm not entirely sure of the fix to any future readers.

Althought for the maintainers of the repo, it would be nice to have some more type checks on perhaps on if the expected row data isn't in alignment with the expected type? Although I'm not sure what this will look like in Python as my skills there are a bit rusty.

**Comment by SteveBruntwood** [comment]
For me, this issue was a empty line at the top of my csv file

**Comment by steven-levey-sp** [comment]
To avoid getting that `NoneType object has no attribute 'strip' error`, I had to make sure that ALL the field names in the CSV were listed. (This defeated the purpose of this option so ultimately I just removed the fieldnames option and kept the delimiter and quotechar options.

So if you have 3 columns in your CSV then you need to mention ALL three columns in the fieldnames option ['col1','col2','col3']

I originally thought that the fieldnames option would allow you to specify the columns you want from your CSV and all other columns would go into a separate spot (based on the csv module docs). It does not.

**Comment by waseemhnyc** [comment]
Thanks for the insight @steven-levey-sp. 
The method is a bit deceiving. I also thought it should function the same way you mentioned. I'll have to update my CSV before loading it in to my script.
