### ISSUE TITLE
OpenSearchVectorSearch doesn't permit the user to specify a field name

### ISSUE THREAD

**Issue by weaversam8** [hwchase17/langchain#2500]
Currently the `OpenSearchVectorSearch` class [defaults to `vector_field`](https://github.com/hwchase17/langchain/blob/26314d7004f36ca01f2c843a3ac38b166c9d2c44/langchain/vectorstores/opensearch_vector_search.py#L189) as the field name of the vector field in all vector similarity searches.

This works fine if you're populating your OpenSearch instance with data via LangChain, but doesn't work well if you're attempting to query a vector field with a different name that's been populated by some other process. For maximum utility, users should be able to customize which field is being queried.

**Comment by weaversam8** [comment]
Done, let me know what you think.

**Comment by naveentatikonda** [comment]
> Done, let me know what you think.

@weaversam8 I just reviewed your PR, everything looks good except a couple of things:
1. We also need to update the [script source function](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/opensearch_vector_search.py#L171) to use custom field name
2. What is the reason behind changing the space_type to “[cosinesimil](https://github.com/hwchase17/langchain/pull/2509/files#diff-81abda330784584487d0923ab67d067871e58b2edd3c80e116f9fd1b03229775R178)” instead of “cosineSimilarity” for “painless_scripting” ? Please refer to this k-NN documentation https://opensearch.org/docs/latest/search-plugins/knn/painless-functions/#function-types

I have addressed these changes in my PR. Also, I have included the changes to add `custom vector_field` and `text_field` while indexing.

**Comment by naveentatikonda** [comment]
@hwchase17 Could you please tag me and @vamshin if any new PRs or github issues are created that are related to OpenSearch. We would like to contribute by addressing those issues and reviewing those PRs.
