### ISSUE TITLE
Add ChatGPT chain/API support

### ISSUE THREAD

**Issue by Glavin001** [hwchase17/langchain#258]
https://github.com/acheong08/ChatGPT or others

**Comment by hwchase17** [comment]
https://twitter.com/hwchase17/status/1599559478042857472?s=20&t=Hb8D3oXynVVvVHjwd4Dp4w and https://gist.github.com/hwchase17/af2230cfc648078e1c4925c9fc183ed1

**Comment by mamigot** [comment]
https://github.com/ibleducation/ibl-ai-chatgpt-langchain

**Comment by hwchase17** [comment]
oh nice! did you tweet it out?

**Comment by mamigot** [comment]
yes sir! https://twitter.com/ibleducation/status/1600926176842723328?s=46&t=YUzfNSZg8WciaHUBD4fuvQ

**Comment by tddschn** [comment]
[ibleducation/ibl-ai-chatgpt-langchain](https://github.com/ibleducation/ibl-ai-chatgpt-langchain) is no longer being updated after Dec 2022, and doesn't support authentication methods other than email + password.

I'd still like to see (official) integration with revChatGPT (more specifically, the [`revChatGPT.V1`](https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/V1.py) even after the official API is out, because revChatGPT can create chat sessions that shows up on chat.openai.com, and allows you to continue the conversation on chat.openai.com later.

My use case: Send multiple prompts crafted with langchain to chat.openai.com programatically, and go to chat.openai.com to continue my conversations.
