### ISSUE TITLE
implement https://arxiv.org/pdf/2211.13892.pdf example selector

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#371]

**Comment by JohnNay** [comment]
here is the motivation:

> The prominent paradigm, i.e., nearest-neighbor-
based exemplar selection strategy, only considers
the relevance between the exemplars and the query.
Yet, selecting nearest neighbors could result in
mostly similar exemplar sets, which can possibly
limit collaboration. We argue that complementarity
should also be considered in the process of ex-
emplar selection, so that the selected exemplar set
could have a higher chance to illustrate the required
reasoning processes.
In practice, it is tricky to decide whether the rea-
soning underlying a set of exemplars are comple-
mentary categorically. We therefore use diversity
as a proxy, since a set of less similar exemplars
is arguably more likely to exhibit complementar-
ity. To that end, we propose a maximal-marginal-
relevance (Carbonell and Goldstein, 1998) (MMR)
based exemplar selection strategy. The idea is to
select exemplars that are relevant to the query while
being diverse enough to be collaborative.
