### ISSUE TITLE
Vertex AI PaLM Support

### ISSUE THREAD

**Issue by Jflick58** [hwchase17/langchain#4532]
### Feature request

If unaware, Google has opened PaLM into public preview in Vertex AI in GCP. This uses different client libraries from the general-use PaLM API that was implemented in the base Langchain support for PaLM. 

### Motivation

As an enterprise user, I'd like to leverage the model endpoints that meet my organization's security and privacy requirements with LangChain. 

### Your contribution

I can open a PR, but as folks from Google like @brotchie having contributed, I wanted to make sure I wasn't duplicating work if I did this.

**Comment by ajndkr** [comment]
@Jflick58 already added here: https://github.com/hwchase17/langchain/pull/3575

**Comment by p13rr0m** [comment]
@ajndkr There are currently two APIs for PaLM. The one that is used in the PR is not the Google Cloud Vertex AI API.

Generative AI
[API](https://developers.generativeai.google/api)
[SDK](https://github.com/google/generative-ai-python)

Vertex AI
[API](https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.preview.language_models)
[SDK](https://github.com/googleapis/python-aiplatform)

**Comment by ajndkr** [comment]
I see! apologies for the confusion.

**Comment by Jflick58** [comment]
WIP branch here: https://github.com/Jflick58/langchain/tree/vertex-ai-palm

**Comment by p13rr0m** [comment]
@Jflick58 Awesome, thanks! Would also be great to have the [embedding model](https://github.com/googleapis/python-aiplatform/blob/9eb2c99cc0b7a43cfed20cc1f8632bef38319236/vertexai/language_models/_language_models.py#L482).

**Comment by pierreembacher** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-13-c18489387fbe>](https://qp1ctyogqim-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230523-060150-RC00_534372501#) in <cell line: 1>()
----> 1 from langchain.chat_models import ChatVertexAI
      2 from langchain.prompts.chat import (
      3     ChatPromptTemplate,
      4     SystemMessagePromptTemplate,
      5     HumanMessagePromptTemplate,

ImportError: cannot import name 'ChatVertexAI' from 'langchain.chat_models' (/usr/local/lib/python3.9/dist-packages/langchain/chat_models/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
