### ISSUE TITLE
Confluence Document Loader not working

### ISSUE THREAD

**Issue by vanshsehgal2001** [hwchase17/langchain#4571]
I tried incorporating confluence document loader in my code. Its throwing some error. Can anyone help me out. Attaching the screenshots and required information.

Code : 
```
from langchain.document_loaders import ConfluenceLoader

loader = ConfluenceLoader(
    url="https://vs2001.atlassian.net/wiki/spaces/<space-key>/pages/<page-id>/<doc-name>",
    username="<user-name>",
    api_key="<api-key>"
)
documents = loader.load(space_key="<space-key>")
print(documents)
```

Here username I use is the prefix in the email till @ symbol
api_key generated in the settings of confluence.

Screenshot of the error: 
<img width="1195" alt="Screenshot 2023-05-12 at 4 30 41 PM" src="https://github.com/hwchase17/langchain/assets/62723522/f1a83ce2-9632-418e-b272-954c7780696a">

Can anyone tell what am I doing wrong here?

**Comment by zvadaadam** [comment]
**AI-generated response by [Steercode](https://steercode.com/) - chat with Langchain codebase **

Based on the code you provided, you are initializing the ConfluenceLoader with a full URL instead of the base URL. The url parameter should only contain the base URL of your Confluence instance, not the full URL of a specific page. Please update your code as follows:
 
```
from langchain.document_loaders import ConfluenceLoader

loader = ConfluenceLoader(
    url="https://vs2001.atlassian.net",
    username="<user-name>",
    api_key="<api-key>"
)
documents = loader.load(space_key="<space-key>")
print(documents)

```  
Replace <user-name> and <api-key> with your actual Confluence username and API key. If you still encounter the AttributeError: 'str', please let me know the full error message, including the line number where the error occurs, so I can help you troubleshoot further.

**Comment by vanshsehgal2001** [comment]
Thanks for replying. I am confused from where to get the confluence username and api key? Can you provide links for the same. It would be really helpful especially regarding username.
