### ISSUE TITLE
ElasticVectorSearch - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by hp0404** [hwchase17/langchain#498]
Hi there,

I'm trying to use huggingface embeddings with elasticvectorsearch, but can't initialize `ElasticVectorSearch` class. 

I run elastic search locally in docker:
```
docker network create elastic
docker run --name es01 --net elastic -p 9200:9200 -it docker.elastic.co/elasticsearch/elasticsearch:8.5.3
```

Then I run the following code:
```python
...
hf = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)
elastic_vector_search = ElasticVectorSearch.from_texts(
    texts,
    hf,
    elasticsearch_url="https://elastic:FR1lY9OEo89NxkbWoj9Z@localhost:9200"
)
```

and get 
```
elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)))
```

It seems that to fix this issue I'd need to provide additional params like cert, etc. but `ElasticVectorSearch` only takes a connection string. 

e.g. when I make a curl request:
```
curl -u elastic https://localhost:9200
```
gives me the following
```
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

when I run the same command with -k, it works
```
curl -u elastic https://localhost:9200 -k
```

it also works when I pass certificate file
```
curl --cacert http_ca.crt -u elastic https://localhost:9200
```

and works in python if I pass cert file:
```python
es_client = elasticsearch.Elasticsearch(elasticsearch_url, ca_certs="http_ca.crt")
```

Any ideas how to fix it?

**Comment by hwchase17** [comment]
@sjwhitmore (the biggest elastic user i know) have you run into this before?

**Comment by kingcoconut** [comment]
Hey @hp0404! Is there a specific reason you are trying to use TLS for this connection? It looks like you are just trying to get this class to initialize the client against your local dev environment? 

The error you're getting is because of the ca_cert that is in your container is self signed. To get this working you're going to need to either:
1. setup real cert (signed by a ca) on the docker instance
2. tell the elasticsearch client to recognize the cert you used to self-sign the cert as being "safe". This is what you have done here:
```
es_client = elasticsearch.Elasticsearch(elasticsearch_url, ca_certs="http_ca.crt")
```
you'll need to pass in the `http_ca.crt` by:
1. making it available to the application as a config or env_var (if env_var set the whole thing as a single string)
2. modify [this line](https://github.com/hwchase17/langchain/blob/2163d064f36b7602162e712b3059fb3302be77cf/langchain/vectorstores/elastic_vector_search.py#L169) to check for it's presence and use it if available

But I'm curious if this whole TLS overhead is actually something you want to do? I typically see people just run without these additional security measures when developing locally

But if you just want to get the connection running locally (without all this TLS overhead) you could try 2 things:
1. change elasticsearch_url string to `http://elastic:FR1lY9OEo89NxkbWoj9Z@localhost:9200`
2. 1. should work but if not it looks like the python client for Elasticsearch allows you to pass in a param `verify_certs=false`

Oh and you should be able to bypass the need for username/password too by booting the docker container with this flag specified `-e "discovery.type=single-node"`. (Checkout the "Running in Development Mode" section here: https://hub.docker.com/_/elasticsearch)

fwiw, the reason this works:
```
curl -u elastic https://localhost:9200 -k
```
is because the -k command is telling curl to not use tls - even though you are specifying "https:".
https://curl.se/docs/manpage.html#-k

also @hwchase17 what's the reason for re-initializing the elasticsearch client [here](https://github.com/hwchase17/langchain/blob/2163d064f36b7602162e712b3059fb3302be77cf/langchain/vectorstores/elastic_vector_search.py#L169)? I'm assuming it will be available via 'cls.client` based on the class initialization? Or does this `from_texts` function connect to a different elastic cluster everytime it's called?

**Comment by hp0404** [comment]
> But I'm curious if this whole TLS overhead is actually something you want to do? I typically see people just run without these additional security measures when developing locally

You're correct. I used whatever I found in docs, but additional security measures make it much harder and aren't needed. 

I managed to run elasticsearch without username/password with the following `docker-compose.yml`.

```
version: "3.7"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
```
