### ISSUE TITLE
cannot import name 'FigmaFileLoader'

### ISSUE THREAD

**Issue by davidvesp** [hwchase17/langchain#5623]
### System Info

langchain==0.0.189
os:windows11
python=3.10.11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import FigmaFileLoader

### Expected behavior

expected:
load the module

error:
ImportError: cannot import name 'FigmaFileLoader' from 'langchain.document_loaders' (C:\Users\xxx\AppData\Local\miniconda3\envs\xxx\lib\site-packages\langchain\document_loaders\__init__.py)

comments:
checked the langchain\document_loaders\__init__.py and there is no reference to FigmaFileLoader

**Comment by rohitf1** [comment]
The issue is arising due to an incorrect import statement. 
In the LangChain library, the FigmaFileLoader is not directly under langchain.document_loaders. 
It is inside a submodule named figma within document_loaders.

You can refer to the file in the repository [here ](https://github.com/hwchase17/langchain/blob/3c6fa9126aa6422084e8c064eda06292d40ac517/langchain/document_loaders/figma.py). 

So, instead of:

`from langchain.document_loaders import FigmaFileLoader
`
You should use:

`from langchain.document_loaders.figma import FigmaFileLoader`

**Comment by leo-gan** [comment]
There is a missed import in the `document_loaders/__init_.py` file. I will fix it.
