### ISSUE TITLE
similarity_search_with_score witn Chroma DB keeps higher score for less relevant documents. 

### ISSUE THREAD

**Issue by 1shershah** [hwchase17/langchain#6046]
### System Info

Python 3.10.6
chromadb==0.3.22
langchain==0.0.194

### Who can help?

similarity_search_with_score witn Chroma DB keeps higher score for less relevant documents. 

```
embeddings = OpenAIEmbeddings(
    model="text-embedding-ada-002",
    openai_api_key = openai.api_key,
    chunk_size=1
)

db = Chroma(collection_name="docs", embedding_function=embeddings, persist_directory=vector_db_path)

question = """What is the rate of arthralgia in the combined RCP and OLP inebilizumab population?"""
[d[1] for d in db.similarity_search_with_score(question, k=5 )]
```

```
[0.3035728335380554,
 0.3159480392932892,
 0.3345768451690674,
 0.3543674945831299,
 0.36075425148010254]
```

```
[d[1] for d in db.similarity_search_with_score(question, k=10 )]

[0.3035728335380554,
 0.3159480392932892,
 0.3345768451690674,
 0.3543674945831299,
 0.36075425148010254,
 0.36337000131607056,
 0.3656774163246155,
 0.36993658542633057,
 0.37518084049224854,
 0.3755079507827759]
```

Seems more like i should be doing (1-score) , to filter more relevant documents.  So i tried to test with similarity threshold of .35 , but then it returns the least similar docs  ( as .30 was more similar ) 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

question = """What is the rate of arthralgia in the combined RCP and OLP inebilizumab population?"""
[d[1] for d in db.similarity_search_with_score(question, k=5 )]
[d[1] for d in db.similarity_search_with_score(question, k=10 )]

### Expected behavior

I would expect higher similarity score for the documents that are earlier in the retruned list ( which the document is more related but has a lower score )

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

The similarity_search_with_score function in LangChain with Chroma DB returns higher scores for less relevant documents because it uses cosine distance as the scoring metric. In cosine distance, a lower score indicates a higher similarity between the query and the document. Therefore, documents with lower scores are more relevant to the query.

### Sources 

- [docs/modules/indexes/vectorstores/examples/chroma.ipynb](https://github.com/hwchase17/langchain/blob/master/docs/modules/indexes/vectorstores/examples/chroma.ipynb)
- [docs/modules/indexes/vectorstores/examples/myscale.ipynb](https://github.com/hwchase17/langchain/blob/master/docs/modules/indexes/vectorstores/examples/myscale.ipynb)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by biagiomaf** [comment]
In my experience, I have a chroma vectorstore with 30000 documents, in windows os, I had same problem, it looked like chromadb similarity search with  search_kwargs={"k": 10} didn't return the actual more relevant documents, what resolved to me was setting the k greater than the whole index, with this statement: vectorstore = Chroma(persist_directory="my_persist_chroma", embedding_function = embeddings).as_retriever(search_kwargs={"k": 50000})   and then if using langchain I made the chan with the max_tokens limitation:   chain = ConversationalRetrievalChain.from_llm(
            llm=CustomChatOpenAI(model=modellorun, temperature=0.5),
            max_tokens_limit=3700,
            return_source_documents=True,
            verbose=True,
            retriever=vectorstore
        ) if you are not using the lanchchain then you can use the docs array after your search it will contain the whole doscs in it but magically they will be sorted correctly so in the first docs you will find the right context, in my case since I wanted the firts 10 docs, I used as contexts docs = docs[:10], I hope it will work for you. Ciao from Italiy Biagio.
