### ISSUE TITLE
Issue: Can't load a public webpage

### ISSUE THREAD

**Issue by jackfrost1411** [hwchase17/langchain#6079]
### I want to load in the webpage below.

Hi,
Trying to extract some webpage using webbaseloader:
"""
loader = WebBaseLoader("https://researchadmin.asu.edu/)
data = loader.load()
"""
But gives the following error:
SSLError: HTTPSConnectionPool(host='researchadmin.asu.edu', port=443): Max retries exceeded with url: / (Caused by 
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get 
local issuer certificate (_ssl.c:1002)')))

It is a public web page. Can anyone help?

**Comment by devstein** [comment]
_Generated by a 🤖_

I found related issues that might be helpful. I did my best to summarize the solutions, but I recommend looking at the related issues yourself.

## Related Issues

### Open Issues

#### [[SSL: CERTIFICATE_VERIFY_FAILED] while load from SitemapLoader](https://github.com/hwchase17/langchain/issues/5483)

This issue is referenced by one PR
- https://github.com/hwchase17/langchain/pull/5485

--- 

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant
