### ISSUE TITLE
Issue: Update dev container configuration

### ISSUE THREAD

**Issue by bamurtaugh** [hwchase17/langchain#6172]
### Issue you'd like to raise.

Hi folks! 👋 My name is Brigit, and I'm a PM on the VS Code team working on dev containers and [their open spec](https://containers.dev/). Thank you so much for [adding a dev container to this repo](https://github.com/hwchase17/langchain/pull/4035) and [langchainjs](https://github.com/hwchase17/langchainjs/pull/1241) - these are fantastic scenarios!

As we're actively working improvements to dev containers and their spec, we've made some changes to the best practices we recommend. For instance, we host an updated set of [images](https://github.com/devcontainers/images) and [templates](https://github.com/devcontainers/templates) as part of the spec in the [devcontainers org](https://github.com/devcontainers), rather than in [vscode-dev-containers](https://github.com/microsoft/vscode-dev-containers). It looks like the image in this repo uses the [deprecated vscode-dev-containers image](https://github.com/hwchase17/langchain/blob/master/.devcontainer/Dockerfile#L5), and perhaps it could leverage the [Poetry Feature](https://containers.dev/features) instead of Poetry installation scripts in the Dockerfile. 

I also tried building the dev container in this repo both in the VS Code Dev Containers extension and GitHub Codespaces, and it didn't work for me as-is (I was stopped at container build), so I think this would be a great opportunity to ensure the dev container works well for all potential contributors too. 

It looks like langchainjs uses an [updated image from the devcontainers org](https://github.com/hwchase17/langchainjs/blob/main/.devcontainer/devcontainer.json#L6), which is great!

### Suggestion:

I'd love to contribute a PR to this repo with an updated dev container (and perhaps with some additional info in the readme or a mini [.devcontainer](https://github.com/hwchase17/langchain/tree/master/.devcontainer) readme), but I wasn't sure the best tests to ensure the repo runs correctly in an updated dev container. Would you be able to share any recommended steps / commands / checks so that I can ensure any dev container updates work well for how folks should be building and running this repo? Info on how you tested and verified the [original PR](https://github.com/hwchase17/langchain/pull/4035) would be a great help too (so I can try the same steps).

Let me know if there's any other info I can provide, and I can also just open a draft a PR if that'd be easiest for discussion. Thanks so much!

cc @vowelparrot and @jj701 as I see your discussion in https://github.com/hwchase17/langchain/pull/4035.

**Comment by jj701** [comment]
@bamurtaugh You could start a PR with improvements.

**Comment by vowelparrot** [comment]
Hi @bamurtaugh , thanks for raising this issue! And thanks for contributing to LangChain. We definitely want to improve the devcontainer experience when developing with LangChain. The short answer is that we'd welcome any PR implementing your recommended changes. If you tag me I'll review it as soon as possible. 

The longer answer is that we are still working on improving the integration testing for many aspects of LangChain, including things like Dev Containers, and still lean heavily on users raising issues such as this one. Apart from spot checks that they build for a couple different scenarios, we will be OK to approve this. We are looking to distribute ownership of key integrations such as this in the future since you and the VSCode team will always have getter knowledge of the best practices for this component than the LangChain core team.

**Comment by bamurtaugh** [comment]
Thank you both! 

I've opened a PR here: https://github.com/hwchase17/langchain/pull/6189.
