### ISSUE TITLE
Add support for typesense vector database

### ISSUE THREAD

**Issue by JohnShahawy** [hwchase17/langchain#931]
I am loving the vector db integrations, maybe @jasonbosco could help integrate [typesense](https://typesense.org/)?

**Comment by jasonbosco** [comment]
Happy to! 

@hwchase17 We have a vector search / store feature in Typesense: https://typesense.org/docs/0.24.0/api/vector-search.html

If you'd be down for an integration, I can take a stab at a PR. Let me know.

**Comment by hwchase17** [comment]
yes would love one! happy to help, but im super familiar with typesense so if wanted to start a pr @jasonbosco that may be most efficient

**Comment by jasonbosco** [comment]
@hwchase17 

> but im super familiar with typesense so if wanted to start a pr

Did you mean to say "but im **NOT** super familiar with typesense" and that you wanted me to start a PR right? 

Just wanted to double-check.

**Comment by jasonbosco** [comment]
@JohnShahawy I took a first stab at a PR that adds support for Typesense here: #1674. However, since I haven't used langchain before, I haven't tested it. I'd love to collaborate with you and get your help to test this PR out and fix any last-mile issues.

Once you're able to get this PR to a working state, I can then write some automated tests based on the tests I see for other vector stores.

**Comment by jasonbosco** [comment]
Or may be @hwchase17, if you're able to help with [the above](https://github.com/hwchase17/langchain/issues/931#issuecomment-1469061077) that would work as well :)

**Comment by garyhlai** [comment]
Would be nice to have Typesense support!
